apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: bad-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: read-file
        command: 
        - /bin/sh
        - -c
        - "cat /app/hello.txt && sleep 3600;"
status: {}
