apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: 200Mi
        cpu: 20m
      requests: 
        memory: 100Mi
        cpu: 10m
  dnsPolicy: ClusterFirst
  restartPolicy: Never

