apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      initContainers:
      - image: busybox
        name: init-file
        command:
        - /bin/sh
        - -c
        - "echo 'hello world' > /hello/hello.txt"
        volumeMounts:
        - name: hello-dir # same as the volume name
          mountPath: /hello
      containers:
      - image: busybox
        name: read-file
        command: 
        - /bin/sh
        - -c
        - "cat /app/hello.txt && sleep 3600;"
        volumeMounts:
        - name: hello-dir # same as the volume name
          mountPath: /app
        resources: {}
      volumes:
      - name: hello-dir
        emptyDir: {}
status: {}
