apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hostpath-busybox
  name: hostpath-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hostpath-busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hostpath-busybox
    spec:
      containers:
      - image: busybox
        name: hostpath-busybox
        command:
        - /bin/sh
        - -c
        - "sleep 3600;"
        volumeMounts:
        - name: log-dir
          mountPath: /logs
      volumes:
      - name: log-dir
        hostPath:
          path: /var/log
status: {}
