apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hostpath-busybox
  name: hostpath-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hostpath-busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hostpath-busybox
    spec:
      containers:
      - image: busybox
        name: hostpath-busybox
        command:
        - /bin/sh
        - -c
        - "sleep 3600;"
        volumeMounts:
        - name: pvc-test
          mountPath: /app
      volumes:
      - name: pvc-test
        persistentVolumeClaim: 
          claimName: testclaim
status: {}
