apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - "sleep 3600;"
    env:
    - name: foo
      value: bar-new
    - name: env
      value: development
    - name: COUNTRY
      valueFrom:
        configMapKeyRef:
          key: country
          name: literal-example
    envFrom:
    - configMapRef:
        name: literal-example
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
